on:
  workflow_dispatch:

env: 
  API_KEY: ${{ secrets.API_KEY }}
  APP_ID: ${{ secrets.APP_ID }}
  AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
  MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}

jobs:
  request-latest-tasks:
    runs-on: ubuntu-latest
    name: Update latest tasks
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Human copilot
        uses: isseikz/human-copilots-action@main
        with:
          user: isseikz
          github-token: ${{ secrets.GITHUB_TOKEN }}
